freelance/config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'clients#index'

  resources :clients do
    resources :projects do
      resources :deadlines
    end
  end
  resources :freelancers
  resources :apis
  resources :sessions
  resources :registrations
  get '/:notable_type/:notable_id/note', to: 'notes#new', as: :new_note
  post '/:notable_type/:notable_id/note', to: 'notes#create', as: :notes

  get '/:source_type/:source_id/document', to: 'documents#new', as: :new_document
  post '/:source_type/:source_id/document', to: 'documents#create', as: :documents
  # api to fetch nonces for users
  namespace :api do
    namespace :v1 do
      resources :users
    end
  end
end

freelance/app/models/client.rb
class Client < ApplicationRecord
  include Concerns::Avatarable

  belongs_to :freelancer

  has_many :projects

  after_create :set_access_code

  def visible_name
    name || 'Antonio'
  end

  def finalised_projects
    projects.map{|p| p if p.finalised?}.compact
  end

  def ongoing_projects
    # projects.where(status: Project.statuses[:going])
    projects.map{|p| p if p.going?}.compact
  end

  def set_access_code
    self.access_code = (0...8).map { (65 + rand(26)).chr }.join
    save
  end
end

freelance/app/controllers/clients_controller.rb
# frozen_string_literal: true

class ClientsController < ApplicationController
  layout 'client_view', only: %i[show]
  before_action :set_client, only: %i[show]

  def index
    @client = Client.new
    @clients = Client.all
  end

  def new
    @client = Client.new

    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    service = CreateClientService.call(current_freelancer, client_params)

    if service.valid?
      @client = service.result[:value]
      respond_to do |format|
        format.html { redirect_to clients_path }
      end
    else
      flash[:alert] = service.errors
    end
  end

  def show; end

  private

  def client_params
    params.require(:client).permit(:name)
  end

  def set_client
    @client = Client.find(params[:id])
  end
end

freelance/app/views/clients/index.html.erb
<div class="container">
  <div class="container" style="padding:15px;">
    <div class="row">
      <div class="col">
        <h3>Clients(<%= current_freelancer.clients.size %>)</h3>
      </div>
      <div class="ml-auto">
        <%= link_to "Add Client", new_client_path, remote: true, class: "btn btn-primary btn-xs-fixed m-xs-0", style: "background-color: green;" %>
      </div>
    </div>
  </div>

  <hr class="solid">

  <% current_freelancer.clients.each do |client| %>
    <%= render 'clients/partials/table_row', client: client %>
  <% end %>
</div>

freelance/app/views/clients/new.js.erb
$('#exampleModal').html("<%= j render ('clients/partials/modal') %>");

$('#exampleModal').modal();

freelance/app/views/clients/show.html.erb
<div class="container" style="padding:15px;">
  <div class="row">
    <div class="col visible_avatar" style="display:inline-flex;">
      <%= image_tag @client.round_avatar, class: "avatar avatar-16 bg-light rounded-circle text-white p-3" %>
      <span style="font-weight: bold;font-size: 20px;margin-left:10px;"><%= @client.name %></span>
    </div>
    <div class="ml-auto">
      <%= link_to "Add Project", new_client_project_path(@client), remote: true, class: "btn btn-primary btn-xs-fixed m-xs-0", style: "background-color: green;" %>
    </div>
  </div>

  <hr class="solid">

  <% @client.projects.each do |project| %>
    <%= render 'projects/partials/table_row', project: project %>
    <hr class="solid">
  <% end %>
</div>