freelance/config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'clients#index'

  resources :clients do
    resources :projects do
      resources :deadlines
    end
  end
  resources :freelancers
  resources :apis
  resources :sessions
  resources :registrations
  get '/:notable_type/:notable_id/note', to: 'notes#new', as: :new_note
  post '/:notable_type/:notable_id/note', to: 'notes#create', as: :notes

  get '/:source_type/:source_id/document', to: 'documents#new', as: :new_document
  post '/:source_type/:source_id/document', to: 'documents#create', as: :documents
  # api to fetch nonces for users
  namespace :api do
    namespace :v1 do
      resources :users
    end
  end
end

freelance/app/views/layouts/_header_menu.html.erb
<nav class="navbar navbar-light bg-light">
  <a class="navbar-brand" href="<%= root_path %>"><%= current_freelancer.brand_name %></a>

  <div class="navbar-nav ml-auto">
    <div class="my-2 row">
      <div class="col" style="border:1px solid green;">
        <i class="bi bi-chat-left-text"></i>
      </div>
      <div class="col" style="border:1px solid green;">
        <i class="bi bi-bar-chart-line"></i>
      </div>
      <div class="col" style="border:1px solid green;">
        <i class="bi bi-bell"></i>
      </div>
      <div class="col visible_avatar" style="display:inline-flex;border:1px solid green;">
        <%= image_tag current_freelancer.round_avatar, class: "avatar avatar-16 bg-light rounded-circle text-white p-1" %>
        <span styles="font-weight: bold;"><%= current_freelancer.visible_name %></span>
      </div>
      <%= link_to "Sign Out", destroy_freelancer_session_path, method: :delete %>
    </div>
  </div>
</nav>

freelance/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lancealot</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
  </head>

  <body>
    <!-- Latest compiled and minified CSS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <%= javascript_tag do %>
      <% if !flash.empty? && flash[:script].present? %>
        <%= raw flash[:script] %>
      <% end %>
    <% end %>
    
    <!-- Header menu -->
    <%= render 'layouts/header_menu' if freelancer_signed_in? %>
    <!-- /Header menu -->
    <div class="">
      <%= yield %>
    </div>
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true"></div>
  </body>
</html>

freelance/app/views/layouts/client_view.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lancealot</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
  </head>

  <body>
    <!-- Latest compiled and minified CSS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <%= javascript_tag do %>
      <% if !flash.empty? && flash[:script].present? %>
        <%= raw flash[:script] %>
      <% end %>
    <% end %>
    
    <!-- Header menu -->
    <%= render 'layouts/header_menu' if freelancer_signed_in? %>

    <div class="container-fluid full-height">
        <div class="row flex-nowrap" style="height: inherit;">
            <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-dark">
                <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
                    <a href="<%= clients_path %>" class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none">
                        <span class="fs-5 d-none d-sm-inline">Clients</span>
                    </a>
                    <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
                      <% current_freelancer.clients.each do |client| %>
                        <li>
                          <a href="<%= client_path(client.id) %>" data-bs-toggle="collapse" class="nav-link px-0 align-middle">
                            <div class="col visible_avatar" style="display:inline-flex;">
                              <%= image_tag client.round_avatar, class: "avatar avatar-16 bg-light rounded-circle text-white p-1" %>
                              <span style="font-weight: bold;font-size: 20px;margin-left:10px;"><%= client.name %></span>
                            </div>
                          </a>
                        </li>
                      <% end %>
                    </ul>
                </div>
            </div>
            <div class="col py-3">
                <div class="container">
                  <div class="">
                    <%= yield %>
                  </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true"></div>
  </body>
</html>

freelance/app/views/layouts/project_view.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lancealot</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
  </head>

  <body>
    <!-- Latest compiled and minified CSS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <%= javascript_tag do %>
      <% if !flash.empty? && flash[:script].present? %>
        <%= raw flash[:script] %>
      <% end %>
    <% end %>
    
    <!-- Header menu -->
    <%= render 'layouts/header_menu' if freelancer_signed_in? %>

    <div class="container-fluid full-height">
        <div class="row flex-nowrap" style="height: inherit;">
            <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-dark">
                <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
                    <a href="<%= client_path(@client) %>" class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none">
                        <span class="fs-5 d-none d-sm-inline">Projects</span>
                    </a>
                    <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
                      <% @client.projects.each do |project| %>
                        <li>
                          <a href="<%= client_project_path(@client, project.id) %>" data-bs-toggle="collapse" class="nav-link px-0 align-middle">
                            <div class="col visible_avatar" style="display:inline-flex;">
                            <%= image_tag project.round_avatar, class: "avatar avatar-16 bg-light rounded-circle text-white p-1" %>
                            <span style="font-weight: bold;font-size: 20px;margin-left:10px;"><%= project.name %></span>
                          </div>
                          </a>
                        </li>
                      <% end %>
                    </ul>
                </div>
            </div>
            <div class="col py-3">
                <div class="container">
                  <div class="full-height">
                    <%= yield %>
                  </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true"></div>
  </body>
</html>