freelance/config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'clients#index'

  resources :clients do
    resources :projects do
      resources :deadlines
    end
  end
  resources :freelancers
  resources :apis
  resources :sessions
  resources :registrations
  get '/:notable_type/:notable_id/note', to: 'notes#new', as: :new_note
  post '/:notable_type/:notable_id/note', to: 'notes#create', as: :notes

  get '/:source_type/:source_id/document', to: 'documents#new', as: :new_document
  post '/:source_type/:source_id/document', to: 'documents#create', as: :documents
  # api to fetch nonces for users
  namespace :api do
    namespace :v1 do
      resources :users
    end
  end
end

freelance/app/models/project.rb
class Project < ApplicationRecord
  include Concerns::Notable
  include Concerns::Avatarable

  belongs_to :client

  has_many :deadlines
  has_many :documents

  enum status: { ready: 0, going: 1, finalised: 2 }

  def finalised?
    deadlines.any? && deadlines.where(status: [Deadline.statuses[:going], Deadline.statuses[:ready]]).empty?
  end

  def going?
    deadlines.where(status: Deadline.statuses[:going]).any?
  end
end

freelance/app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < ApplicationController
  layout 'project_view', only: %i[show]
  before_action :set_project, only: %i[show]
  before_action :set_client

  def index
    @project = Project.new
    @projects = Project.all
  end

  def new
    @project = Project.new

    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    service = CreateProjectService.call(@client, project_params)

    if service.valid?
      @project = service.result[:value]
      redirect_to client_path(@client)
    else
      flash[:alert] = service.errors
    end
  end

  def show; end

  private

  def project_params
    params.require(:project).permit(:name, :category, :deadline)
  end

  def set_project
    @project = Project.find(params[:id])
  end

  def set_client
    @client = Client.find(params[:client_id])
  end
end

freelance/app/views/projects/partials/_add_project.html.erb
<!-- Button trigger modal -->
<!--
<%= link_to 'Add client', new_client_path, remote: true, class: "btn btn-#{current_freelancer.clients.empty? ? 'secondary' : 'default'} btn-xs-fixed m-xs-0" %>
-->
<%= render 'projects/partials/modal' %>
<button type="button" class="btn btn-<%="#{@client.projects.empty? ? 'secondary' : 'default'}"%> btn-xs-fixed m-xs-0" data-toggle="modal" data-target="#exampleModal">
  Add Project
</button>

freelance/app/views/projects/partials/_modal.html.erb
<!-- Modal -->
<%= form_for(@project, url: client_projects_path, method: :post) do |form| %>
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Create Project</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <div class="form-control">
            <%= form.label :name %>
            <%= form.text_field :name %>
          </div>
          <div class="form-control">
            <%= form.label :category %>
            <%= form.text_field :category %>
          </div>
          <div class="form-control">
            <%= form.label :deadline %>
            <%= form.date_field :deadline %>
          </div>
        </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <%= form.submit "Create", class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

freelance/app/views/projects/partials/_table_row.html.erb
<div class="row" styles="display: flex; align-items: center;cursor: pointer;" onclick="window.location.assign('<%= (client_project_path(@client, project)) %>');">
  <div class="col visible_avatar" style="display:inline-flex;">
    <i class="bi bi-file"></i>
    <span style="font-weight: bold;font-size: 20px;margin-left:10px;"><%= project.name %>, <%= project.category %></span>
  </div>
  <div class="col ml-auto">
    <span>Deadline <%= project.deadline&.strftime('%d %b %Y') %>, </span>
    <span>Activity <%= project.status.capitalize %></span>
  </div>
</div>