freelance/config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'clients#index'

  resources :clients do
    resources :projects do
      resources :deadlines
    end
  end
  resources :freelancers
  resources :apis
  resources :sessions
  resources :registrations
  get '/:notable_type/:notable_id/note', to: 'notes#new', as: :new_note
  post '/:notable_type/:notable_id/note', to: 'notes#create', as: :notes

  get '/:source_type/:source_id/document', to: 'documents#new', as: :new_document
  post '/:source_type/:source_id/document', to: 'documents#create', as: :documents
  # api to fetch nonces for users
  namespace :api do
    namespace :v1 do
      resources :users
    end
  end
end

freelance/app/models/deadline.rb
class Deadline < ApplicationRecord
  include Concerns::Notable

  belongs_to :project

  has_many :documents

  enum status: { ready: 0, going: 1, finalised: 2 }, _default: :going
end

freelance/app/controllers/deadlines_controller.rb
# frozen_string_literal: true

class DeadlinesController < ApplicationController
  before_action :set_project
  before_action :set_client
  before_action :set_deadline, only: %i[show]

  def new
    @deadline = Deadline.new

    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    service = CreateDeadlineService.call(@project, deadline_params)

    if service.valid?
      @deadline = service.result[:value]
      respond_to do |format|
        format.html { redirect_to client_project_path(@client, @project) }
      end
    else
      flash[:alert] = service.errors
    end
  end

  # Workaround, lack of time
  def show
    if @deadline.finalised?
      @deadline.going!
    else
      @deadline.finalised!
    end
    redirect_to client_project_path(@client, @project)
  end

  private

  def deadline_params
    params.require(:deadline).permit(:name)
  end

  def set_project
    @project = Project.find(params[:project_id])
  end

  def set_client
    @client = Client.find(params[:client_id])
  end

  def set_deadline
    @deadline = Deadline.find(params[:id])
  end
end

freelance/app/views/deadlines/partials/_modal.html.erb
<!-- Modal -->
<%= form_for(@deadline, url: client_project_deadlines_path, method: :post) do |form| %>
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Create Deadline</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="form-control">
        <%= form.label :name %>
        <%= form.text_field :name %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <%= form.submit "Create", class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

freelance/app/views/deadlines/partials/_table_row.html.erb
<div class="row" styles="display: flex; align-items: center;">
  <div class="col">
    <a href="<%= client_project_deadline_path(@client, @project, deadline) %>">
      <% if deadline.finalised? %>
        <i class="bi bi-check-circle-fill"></i>
      <% else %>
        <i class="bi bi-check-circle"></i>
      <% end %>
    </a>
  </div>
  <div class="col">
    <span><%= deadline.name %></span>
  </div>
  <div class="col">
    <%= link_to "Notes", new_note_path(deadline.class.name.downcase, deadline.id), remote: true, class: "btn btn-#{@client.projects.empty? ? 'secondary' : 'default'} btn-xs-fixed m-xs-0" %>
  </div>
  <div class="col">
    <%= link_to "Documents", new_document_path(deadline.class.name.downcase, deadline.id), remote: true, class: "btn btn-#{@client.projects.empty? ? 'secondary' : 'default'} btn-xs-fixed m-xs-0" %>
  </div>
  <div class="col ml-auto">
    <div class="row">
      <div class="col">
        <i class="bi bi-stop-fill"></i>
      </div>
      <div class="col">
        <i class="bi bi-play"></i>
      </div>
      <div class="col">
        0:00
      </div>
    </div>
  </div>
</div>